application:
  version: 1.0-Demo
  description: Demo version for bank cards

server:
  port: 9090

jwt:
  token:
    secret:
    expired: 3600000

logging:
  file:
    name: app.log

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/migration/changelog-master.yml
    url: jdbc:postgresql://
    user:
    password:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://
    username:
    password: