application:
  version: 1.0-Demo
  description: Demo version for bank cards

server:
  port: 9090

jwt:
  token:
    secret: jjwtrestapplicationspecialsecret
    expired: 3600000
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/migration/changelog-master.yml
    url: jdbc:postgresql://localhost:5432/bank-cards
    user: postgres
    password: iamroot

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank-cards
    username: postgres
    password: iamroot